version: "3"

services:
  app:
    container_name: app
    build:
      context: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s ./run.sh
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    restart: always
    networks:
      - fullcycle-node

  db:
    container_name: db
    build:
      context: mysql
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle-node

  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - 8080:80
    depends_on:
      - app
    restart: always
    networks:
      - fullcycle-node

networks:
  fullcycle-node:
    driver: bridge
